#为避免和前端端口冲突，修改为9090
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final?serverTimezone=GMT%2b8
    username: root
    password: HQM0208ylq
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
